### ISSUE TITLE
list of acceptable resolutions

### ISSUE THREAD

**Issue by tavalin** [TBSniller/piccap#10]
Hi - me again.

After the previous issue where the default capture resolution is set to 360 x 180 which doesn't work for my TV - is there a way to determine acceptable capture resolutions?

**Comment by TBSniller** [comment]
Hey,
actually not really. It also seems to be different from application to application. With libdile_vt we may will have a independet solution for that. But actually is earlier than our other early stuff.

Maybe one solution will be to enable logging, start capture and get the supported resolution from /var/log/messages. As far as we know its stated there after a start

**Comment by dimitrij2k** [comment]
180 x 90 x 30fps/60fps/0fps
360 x 180 x ……
640 x 360 x ……

just try it…

**Comment by TBSniller** [comment]
maybe we can get the information for available resolutions from the backends and display them in a drop down-menu in future.

**Comment by TBSniller** [comment]
Over time we have collected some resolutions. They are now available in a drop down menu in settings page.
