### ISSUE TITLE
Green bars

### ISSUE THREAD

**Issue by gomble** [TBSniller/piccap#11]
I installed piccap and i have following error: capture is running and i can see the screen in hyperion but my screen shows green bars, on all hdmi inputs, but not at youtube app or other apps on lg
![image](https://user-images.githubusercontent.com/6769445/145710622-ddf3b3aa-08da-4770-b94c-dffbcac54282.jpeg)
https://user-images.githubusercontent.com/6769445/145710629-5c6ccb6a-534f-4bf8-92cd-358161fbbed4.MOV

**Comment by TBSniller** [comment]
Hey, as already stated by Mariotaku and JohnPaul in the discord, at this moment we can't do something about that. These are known issues laying on HDMI inputs and using libvt. There is already a alternative (a capture layer below libvt - more near to system) in development, but at the moment not really released. Stay tuned.

**Comment by gomble** [comment]
> Hey, as already stated by Mariotaku and JohnPaul in the discord, at this moment we can't do something about that. These are known issues laying on HDMI inputs and using libvt. There is already a alternative (a capture layer below libvt - more near to system) in development, but at the moment not really released. Stay tuned.

Okay thank you

**Comment by nnmdd** [comment]
Hi. I think i resolved issue.
Seems like it's scaling bug because of when i changed 16:9 resolution to dividable by 8 (128x72 exacly) no any sort of green bar on screen visible. And if i use any other 16:9 res - green bar appears at bottom.
Moreover piccap service on my tv starts only with listed 16:9 resolutions and didn't start with default 360x180 at all
https://pacoup.com/2011/06/12/list-of-true-169-resolutions/

tv lg c1rla 3.11.15 webos 6.0

**Comment by TBSniller** [comment]
@nnmdd Oh this really is quite interesting. Are you also using libvt?

**Comment by nnmdd** [comment]
no, i have newer model of tv and use libvtcapture
Piccap 0.21
Service even not start with any other variant

**Comment by gomble** [comment]
Changing the resolution did not help.
I updated to 0.22 and testet both: libdile_vt and libvt+libgm.

With libvt+libgm. i got the greenbars again. I tested all resoltuions from this site: https://pacoup.com/2011/06/12/list-of-true-169-resolutions/

With libdile_vt i am getting no greenbars but lines at the top
![image](https://user-images.githubusercontent.com/6769445/149643262-f56375a7-ba24-4d15-922b-7b1f80bd3a21.png)

But in hyperion i see a mix of green and the tv picture:
![image](https://user-images.githubusercontent.com/6769445/149643106-b40c35e4-01cf-4280-bcb6-e29f14029965.png)

**Comment by nnmdd** [comment]
piccap 0.2.2
tested with libvtcapture
resolutions where both parametrs diviable by 2 dosnt add artifacts: 96x54, 128x72, 160x90, 192x108, 320x180 tested
![vivaldi_4XgdW74WR1](https://user-images.githubusercontent.com/97770937/149684843-2b04de65-b489-43c8-9392-c33ad2603df6.png)
![vivaldi_E5KkHLdXTA](https://user-images.githubusercontent.com/97770937/149684844-3d41bf24-0bb6-4138-929d-85b58f83b76d.png)
![vivaldi_UyfiSlnU25](https://user-images.githubusercontent.com/97770937/149684845-399342d3-29a8-475c-9b96-7c31b9a65f87.png)

resolutions with last digit odd will give green bar in right bottom:
![vivaldi_3xNqTdj0Pa](https://user-images.githubusercontent.com/97770937/149684815-d6ed21f5-0d97-4688-9421-af30b9ffcb79.png)
![vivaldi_1ZKUKrGIHx](https://user-images.githubusercontent.com/97770937/149684817-9801045c-eadd-4b2e-8737-105f615e1e3b.png)
![vivaldi_CatE10FsmU](https://user-images.githubusercontent.com/97770937/149684818-c2ef11c3-6f79-4cbc-8ae3-3f7887520df0.png)

any other options like libvt or libdile_vt just stops service from working before tv reboot

**Comment by gomble** [comment]
i found out that if a start youtube everything works:
![image](https://user-images.githubusercontent.com/6769445/149845738-3a44177c-a082-43c6-951d-39d8ba543c67.png)

only if i switch to my enigma2 receiver (gigablue trio4k) i get green mix
![image](https://user-images.githubusercontent.com/6769445/149845780-07eb0f79-f0d3-4b83-b649-a13b83fe6115.png)

**Comment by gomble** [comment]
Okay i found out that it is on all hdmi inputs and not only my enigma2 receiver

HDMI Inpu #2 
![image](https://user-images.githubusercontent.com/6769445/149846966-8dcac18b-bf68-4a87-8479-b1b485061e4a.png)

**Comment by gomble** [comment]
![image](https://user-images.githubusercontent.com/6769445/150619216-4ac5a5bf-0ab5-4164-a421-e056fee0a42f.png)

woow with 0.2.3 its working, this is so cool thank you 👍

**Comment by gomble** [comment]
![image](https://user-images.githubusercontent.com/6769445/150624377-14367eeb-c749-4d06-9dae-be00a1e2d45f.jpeg)

This is amazing !
