### ISSUE TITLE
Piccap doesn't work via GUI, SSH works very well

### ISSUE THREAD

**Issue by satgit62** [TBSniller/piccap#14]
Report here on my progress regarding Ambilight with LG-TV Piccap and Hyperion.
LG OLED 65B7D year 2017 with WebOs 3.9
Webosbrew with Piccap 1.0. Everything installed according to the instructions and the permission file for the Homebrew Channel set to: {"public": ["org.webosbrew.hbchannel.service / *"], "ares.webos.cli": ["org.webosbrew.hbchannel. service / * "]}
Piccap GUI **does not work / does not start and is also not saved**. Start manually via ssh command : "/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos_libvt -a 192.168.x.x" **works great/ perfectly** with Hyperion NG, and in consoles stands the following:
[EGL] Display, major = 1, minor = 4
[EGL] Surface size: 192x108
[EGL] init complete
[VT] VT_CreateVideoWindow
[VT] window_id=0
[VT] VT_AcquireVideoWindowResource
[VT] resource_id=85
[VT] VT_CreateContext
[VT] context_id=1217344
[VT] VT_SetTextureResolution
[VT] VT_SetTextureSourceRegion
[VT] VT_SetTextureSourceLocation
[VT] VT_RegisterEventHandler
Start connection loop.
Hyperion gets the data from Piccap and everything is OK. **Something does not work when called via GUI**, although all libraries are available.
If I enter "find / | grep libvt" in ssh, this comes out:
/etc/pmlog.d/libvt.conf
/etc/pmlog.d/libvtv.conf
/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos_libvt
/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos_libvtcapture
/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/setlibvtcaptureperms.sh
/mnt/lg/appstore/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos_libvt
/mnt/lg/appstore/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos_libvtcapture
/mnt/lg/appstore/developer/apps/usr/palm/services/org.webosbrew.piccap.service/setlibvtcaptureperms.sh
/usr/lib/libvt.so.1
/usr/lib/libvt.so.1.0.0
/usr/lib/libvtv.so.1
/usr/lib/libvtv.so.1.0.0
/usr/lib/opkg/info/libvt1.control
/usr/lib/opkg/info/libvt1.list
/usr/lib/opkg/info/libvt1.postinst
/usr/lib/opkg/info/libvtv1.control
/usr/lib/opkg/info/libvtv1.list
/usr/lib/opkg/info/libvtv1.postinst
/old_root/etc/pmlog.d/libvt.conf
/old_root/etc/pmlog.d/libvtv.conf
/old_root/usr/lib/libvt.so.1
/old_root/usr/lib/libvt.so.1.0.0
/old_root/usr/lib/libvtv.so.1
/old_root/usr/lib/libvtv.so.1.0.0
/old_root/usr/lib/opkg/info/libvt1.control
/old_root/usr/lib/opkg/info/libvt1.list
/old_root/usr/lib/opkg/info/libvt1.postinst
/old_root/usr/lib/opkg/info/libvtv1.control
/old_root/usr/lib/opkg/info/libvtv1.list
/ld_root/usr/lib/opkg/info/libvtv1.postinst
If I enter "find / | grep libgm" in ssh this comes out:
/usr/lib/libgm.so.1
/usr/lib/libgm.so.1.0.0
/usr/lib/libgmodule-2.0.so.0
/usr/lib/libgmodule-2.0.so.0.4000.0
/usr/lib/libgmp.so.3
/usr/lib/libgmp.so.3.4.1
/usr/lib/opkg/info/libgmp3.control
/usr/lib/opkg/info/libgmp3.list
/usr/lib/opkg/info/libgmp3.postinst
/old_root/usr/lib/libgm.so.1
/old_root/usr/lib/libgm.so.1.0.0
/old_root/usr/lib/libgmodule-2.0.so.0
/old_root/usr/lib/libgmodule-2.0.so.0.4000.0
/old_root/usr/lib/libgmp.so.3
/old_root/usr/lib/libgmp.so.3.4.1
/old_root/usr/lib/opkg/info/libgmp3.control
/old_root/usr/lib/opkg/info/libgmp3.list
/old_root/usr/lib/opkg/info/libgmp3.postinst.
What else should I try to be able to start the whole Piccap app via GUI ?
Greetings satgit62

**Comment by TBSniller** [comment]
Hey, 
do you use WebOS 3?

**Comment by satgit62** [comment]
Yes, WebOs 3.9

**Comment by TBSniller** [comment]
IIRC I had done a error, so PicCap wasn't working on TVs earlier to WebOS4.
JohnPaul began to rewrite the service and also fixed this issue, but its not finished yet, you may compile it on your own from here: https://github.com/Informatic/piccap/tree/service-cleanup
We are also rewriting the service native to get it independent of NodeJS, but this is also not ready 
So if you don't want to compile, you have to wait a bit till everything is ready. Because we all do this in our freetime, we can't say when this will be

**Comment by satgit62** [comment]
Thanks for a quick reply, I will wait, maybe it will come as a Christmas present.

**Comment by derstrassi** [comment]
Also have an LG OLED 65B7D, same issue. Tried the branch you mentioned (https://github.com/Informatic/piccap/tree/service-cleanup) but makes no difference. Is your branch (task/native-service) ready to be tried?

**Comment by satgit62** [comment]
Hey,
I can start the service via ssh and Hyperion/Ambilight works very well but not via GUI. Do the same with you too?

**Comment by derstrassi** [comment]
Yes, manually via command line works but piccap cannot start the service. Unfortunately I do not know how to view the logs or how to debug this.

**Comment by TBSniller** [comment]
It's doesn't clear enough for me what you guys have tried.
To sum up both of you have problem launching on WebOS3, right? 
Both of you have tried the branch from @informatic and it doesn't work either? I'm only remembering he gave someone a new copy and it did fix something. I really don't know if it was the WebOS version issue.

My branch defently can't work together with PicCap at the moment. The necessary things like loading/setting and saving settings isn't implemented yet. Yet it is only possible to speak directly to the Luna service e.g using luna-calls For Start/Stop/Status. 

For now you guys can play around with hyperion-webos, which is located in the service directory of PicCap. There you can see help with ./hyperion-webos --help, what youve already done 

If you guys want to test things out, you can hang on the OpenLG Discord and wait for us to announce another testing builds regarding PicCap - but please be patient

**Comment by derstrassi** [comment]
I've tried the branch from @Informatic which has a working GUI (load/save works on my webOS 3 TV) but cannot start the service (error message: `{ "errorCode": -1, "returnValue": false, "errorText": "Message status unknown." }` )

**Comment by trollsoft7** [comment]
hello, as I have webOS 3.9 as well, I tried your steps with CLI-Start (GUI does not work):`root@LGwebOSTV:~# /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos_libvt -a 1
0.0.0.109
[EGL] Display, major = 1, minor = 4
hyperion-webos_libvt: /home/tbsniller/vscode/hyperion-webos_libvt/hyperion-webos/src/capture.c:206: egl_init: Assertion `eglGetError() == EGL_SUCCESS' failed.
[11]+  Stopped (signal)          /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos_libvt -a 10.0.0.109
root@LGwebOSTV:~# `
What can I do to get more information about this error? xxx.109 is my Hyperbian Raspberry. Do you have an idea? Thanks.

**Comment by Informatic** [comment]
You can try downloading latest development artifacts zip from here: https://github.com/webosbrew/hyperion-webos/actions/runs/1568099580 and launch it manually with `-b libdile_vt`

**Comment by trollsoft7** [comment]
Thank you @Informatic for trying to help me, but I am to noobie to know what to do with your instructions. Don't bother to help me, I just stay patient and wait for your release. Thanks again!

**Comment by satgit62** [comment]
With the pre-release version (**org.webosbrew.piccap_0.2.2_all.ipk**) everything works **perfectly**, including the **GUI**. Thanks to @TBSniller & Co.
LG OLED 65B7D model 2017 with WebOs 3.9.
Greeting satgit62

**Comment by TBSniller** [comment]
vt is depreciated by now. With latest version we support webOS 3.4 and above.
