### ISSUE TITLE
Stop working after some time

### ISSUE THREAD

**Issue by PinkyJie** [TBSniller/piccap#16]
Thanks for this great project, it's much easier than the HDMI splitter/capture flow and works with the native app in the TV.

The issue I got is: after running some time it just stops working somehow. The UI still shows `Capture running: true`, but all LED are dark and the "Remote control" UI in Hyperion shows nothing for "Source selection" (normally it shows a webos flatbuffer server there). I need to click "Start" again in the PicCap UI to make it work again. I guess the app process somehow crashes? Is there any logs I can check?

WebOS firmware version: 05.00.15

**Comment by rmp63526** [comment]
Hi, same problem here. Afterturning of the the TV the Led's stays off. Only after i push start again the leds works again.

**Comment by PinkyJie** [comment]
There is a WIP PR #6 which will restart the service once it's stopped. I followed the guide there installing that build and it works. So closing this for now.
