### ISSUE TITLE
Piccap app won't Start the service automatically

### ISSUE THREAD

**Issue by rmp63526** [TBSniller/piccap#19]
Hi @TBSniller , when i turn off the Tv and turn it back on, the Piccap app won't Start the service automatically.
I always have to open piccap and start it manually.

By the way, thx for this amazing program and the effort you provide for us.

webOS TV 4.4.0 LGwebOSTV

/ # grep -h -E '"(hardware_id|core_os_release|product_id|webos_manufacturing_ver
sion|board_type)"' /var/run/nyx/*
"board_type": "M16P_DVB",
"hardware_id": "HE_DTV_W18H_AFADABAA",
"product_id": "OLED65B87LC",
"core_os_release": "4.4.0-9",
"webos_manufacturing_version": "05.40.09",
/ #

**Comment by denimjeans** [comment]
Hi, I have the same issue, I am using libvt. 
During installation (repo) there was a note anywhere that autorun is not working for TVs build before 2018. Not sure if it was fixed meanwhile.

**Comment by rmp63526** [comment]
My problem solved with 0.2.2 version!
