### ISSUE TITLE
Service crashes sometimes & not restarting

### ISSUE THREAD

**Issue by grosseskino** [TBSniller/piccap#20]
Hi.

First of all a HUGE THANKS to the developers of this project, love it!

I installed piccap and it is working fine for some time (sometime 2 hours), then the service crashes and won't restart.
Logging in through ssh and running "libvtcapture -a IP" restarts the service, but then I have to keep the ssh session open..

I have webos 5.3.0-19 running.

Are there any logs for the service?
How is the service called?
Where is the service registered for autostart? 
I couldn't find anything in "/etc/systemd/services/"

**Comment by Informatic** [comment]
Startup is handled by `/var/lib/webosbrew/init.d/piccapautostart` symlink-to-a-script.

Which version are you running?

[On v0.2.2 we are currently testing](https://github.com/TBSniller/piccap/releases/tag/0.2.2) we have a major overhaul of how we handle the background service, plus a bunch of stability improvements. It's likely this will help.

**Comment by snaga1004** [comment]
Maybe an useful side note. The autostart worked for me only after disabling the "quickStart+" function in the general tv settings.

**Comment by gomble** [comment]
Same for me if i power off the tv and start it again picap does not start automatically. I have to open picap and have to stop and start again.

**Comment by grosseskino** [comment]
I am running version 0.1.0.
installed it through the homebrew-channel.

disabling the "quickStart+" function in the general tv settings was a great idea, thanks for that!
the service is then autostarting after crashing, when "quickStart+" is enabled the tv needs a reboot through ssh or hard power off to start the service on boot.

the piccap services still crashes every once in a while.

i just updated piccap to version 0.2.6
will keep you posted if the issue is solved

**Comment by grosseskino** [comment]
as of version 0.2.6 piccap is running fine.
thanks for your support!

closing this issue
