### ISSUE TITLE
PicCap UI not working on 3.4

### ISSUE THREAD

**Issue by willscottuk** [TBSniller/piccap#24]
Hi,

Carrying on from some of the Discord chat over the weekend - now that hyperion-webos is fixed for 3.4.0 / the M16_DVB board.

While the UI loads, root status never loads, nor is the UI able to save or load configuration, or start/stop the service.

![image](https://user-images.githubusercontent.com/28684940/150866159-18f1087f-d9c5-4ace-b45a-4afa94249abd.png)

The only functioning button is the "Reboot TV" button.

```
"board_type": "M16_DVB",
"hardware_id": "HE_DTV_W16N_AFADABAA",
"product_id": "49UH750V-ZA",
"core_os_release": "3.4.0-5908",
"webos_manufacturing_version": "05.60.25"
```

WebOS homebrew 0.4.0 installed, root reported as "ok" in homebrew.

**Comment by Informatic** [comment]
Note: service is launched when called and `elevate-service` is properly executed, but calls still error out with `Denied method call for category {}`...

We probably need some extra patching in `/var/palm/ls2-dev`.

**Comment by PaoloVallesi** [comment]
From a newbie prospective, i can confirm that the issue is strictly ui related. I took a look to the script.js file and tried the various calls and they are all working correctly:

```
luna-send -n 1 -f luna://org.webosbrew.piccap.service/isRoot '{}'
{
    "rootStatus": true,
    "returnValue": true,
    "backmsg": "Running as root!"
}

luna-send -n 1 -f luna://org.webosbrew.piccap.service/isRunning '{}'
{
    "returnValue": true,
    "isRunning": true
}

```
still, from the ui, the situation is what @Informatic already described.

For now i started the service using
`luna-send -n 1 -f luna://org.webosbrew.piccap.service/getSettings '{}'`
to get the json config. Modified as needed a set with 
`luna-send -n 1 -f luna://org.webosbrew.piccap.service/setSettings '{"returnValue": true, "backend": "l
ibdile_vt", "port": 19400, "width": 360, "height": 180, "captureUI": true, "ip": "192.168.1.26", "fps": 0, "backmsg": "S
ettings got successfully!", "captureVideo": true, "autostart": true}'`

then with
`luna-send -n 1 -f luna://org.webosbrew.piccap.service/start '{}'`
the service started with no problem

as said, the ui is still stuck with `"Root status: Loading status..."` and with the buttons not working returning the message @Informatic  already reported so that will definetly need a fix.

**Comment by MichaelSchemmer** [comment]
@PaoloVallesi Thanks so much for the info on starting it via luna-send. I managed to get it working, but the backlights only display white light, which dims and brightens according to the scene.
I have an Nvidia Shield with the Hyperion Grabber installed that works perfectly well with colour.
Any ideas why colour isn't working with the LG implementation?

**Comment by davnozdu** [comment]
Hello.
My WebOS 3.4 have same bug.
I am send this settings, but service  not start

```
# luna-send -n 1 -f luna://org.webosbrew.piccap.service/setSettings '{"backend": "l ibdile_vt", "port": 19400, "width
": 360, "height": 180, "captureUI": true, "ip": "192.168.0.168", "fps": 0, "backmsg": "S ettings got successfully!", "c
aptureVideo": true, "autostart": true}'
{
    "returnValue": true,
    "backmsg": "Settings set successfully!"
}

```
Then I am try to start, I am get error

```
# luna-send -n 1 -f luna://org.webosbrew.piccap.service/start '{}'
{
    "returnValue": true,
    "backmsg": "ERROR: Capture main init failed!"
```

**Comment by kduchrow** [comment]
For me there was a small mistake in  "backend" section (only a whitespace to much).
I've added a fix for me in "with" so probably you should edit this.

This one worked for me: 
`
luna-send -n 1 -f luna://org.webosbrew.piccap.service/setSettings '{
    "returnValue": true,
    "backend": "libdile_vt",
    "port": 19400,
    "width": 320,
    "height": 240,
    "captureUI": true,
    "ip": "XX.XX.XX.XX",
    "fps": 0,
    "backmsg": "Settings got successfully!",
    "captureVideo": true,
    "autostart": false
}'
`
And to Start and Stop : 

`luna-send -n 1 -f luna://org.webosbrew.piccap.service/start '{}'
`
`luna-send -n 1 -f luna://org.webosbrew.piccap.service/stop '{}'
`

**Comment by davnozdu** [comment]
> For me there was a small mistake in "backend" section (only a whitespace to much). I've added a fix for me in "width" so probably you should edit this.
> 
> This one worked for me:
> 
> ```shell
> luna-send -n 1 -f luna://org.webosbrew.piccap.service/setSettings '{
>     "returnValue": true,
>     "backend": "libdile_vt",
>     "port": 19400,
>     "width": 320,
>     "height": 240,
>     "captureUI": true,
>     "ip": "XX.XX.XX.XX",
>     "fps": 0,
>     "backmsg": "Settings got successfully!",
>     "captureVideo": true,
>     "autostart": false
> }'
> ```
> 
> And to Start and Stop :
> 
> ```shell
> luna-send -n 1 -f luna://org.webosbrew.piccap.service/start '{}'
> ```
> 
>  ```shell
> luna-send -n 1 -f luna://org.webosbrew.piccap.service/stop '{}'
> ```

Super - it is work.
Thanks

**Comment by RestOp** [comment]
Hi guys,

are you staring these commands 
![image](https://user-images.githubusercontent.com/46259141/153495360-e78c74fc-a9c5-4883-acec-1d5818595389.png)

from SSH or how?
If i start them from SSH i get no answer like...
![image](https://user-images.githubusercontent.com/46259141/153495430-d60a16db-36bd-40d3-99af-f7d1bb30b44c.png)

**Comment by ouchkilljoys** [comment]
> > For me there was a small mistake in "backend" section (only a whitespace to much). I've added a fix for me in "width" so probably you should edit this.
> > This one worked for me:
> > ```shell
> > luna-send -n 1 -f luna://org.webosbrew.piccap.service/setSettings '{
> >     "returnValue": true,
> >     "backend": "libdile_vt",
> >     "port": 19400,
> >     "width": 320,
> >     "height": 240,
> >     "captureUI": true,
> >     "ip": "XX.XX.XX.XX",
> >     "fps": 0,
> >     "backmsg": "Settings got successfully!",
> >     "captureVideo": true,
> >     "autostart": false
> > }'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And to Start and Stop :
> > ```shell
> > luna-send -n 1 -f luna://org.webosbrew.piccap.service/start '{}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > luna-send -n 1 -f luna://org.webosbrew.piccap.service/stop '{}'
> > ```
> 
> Super - it is work. Thanks

Tried this didnt work for me

Kept getting this error

```
root@LGwebOSTV:~# luna-send -n 1 -f luna://org.webosbrew.piccap.service/start '{
}'
{
    "errorCode": -1,
    "returnValue": false,
    "errorText": "Message status unknown."
}
```

```
root@LGwebOSTV:~# grep -h -E '"(hardware_id|core_os_release|product_id|webos_man
ufacturing_version|board_type)"' /var/run/nyx/*
    "board_type": "M16_DVB",
    "hardware_id": "HE_DTV_W16N_AFADABAA",
    "product_id": "65UH652T-TA",
    "core_os_release": "3.4.0-5908",
    "webos_manufacturing_version": "05.60.25",
```

**Comment by TBSniller** [comment]
Please check out latest version (currently 0.4.1) this is tested working on webOS 3.4.
