### ISSUE TITLE
LG OLED65B6V low FPS

### ISSUE THREAD

**Issue by EmmanuelVella** [TBSniller/piccap#28]
Hello,

I just rooted my OLED B6 (2016) and installed the app. I get the stream in hyperion, but very low FPS (I would say about ~5 fps).

I used the following command : 

```
luna-send -n 1 -f luna://org.webosbrew.piccap.service/setSettings '{"returnValue": true, "backend": "libdile_vt", "port": 19400, "width": 192, "height": 108, "captureUI": false, "ip": "192.168.1.149", "fps": 30, "backmsg": "Settings got successfully!", "captureVideo": true, "autostart": true}'
```

Tried to use lib_vt, not working.

My TV :
```
"board_type": "K2L_DVB",
"hardware_id": "HE_DTV_W16K_AFADABAA",
"product_id": "OLED65B6V-Z",
"core_os_release": "3.4.0-5709",
"webos_manufacturing_version": "05.60.25",
```

Could someone help ? Thank you !

**Comment by Informatic** [comment]
https://github.com/webosbrew/hyperion-webos/issues/30 That's the issue. We'll fix this soon.

**Comment by EmmanuelVella** [comment]
Ok thank you very much !
