### ISSUE TITLE
UI cannot be navigated via regular remote

### ISSUE THREAD

**Issue by tuxuser** [TBSniller/piccap#31]
Using a TV with a regular (not so-called "Magic remote") - the piccap application is not possible to use.

- Boxes or buttons are not highlightable / choosable
- No cursor for choosing elements appears either

Any help on what I am doing wrong is appreciated
cheers

**Comment by Lupin62** [comment]
Have you confirmed this?  I'm in the same boat and have been pulling my hair out trying to get things working via command line which I'm not as well versed in.  If it is only able to be navigated via Magic Remote a notice on the main page would likely save others from a huge headache.

**Comment by Informatic** [comment]
Yes, that is a known issue. You can try connecting a mouse to the TV to navigate the UI for now.

**Comment by mcphailmonator** [comment]
I've been using the LG tv remote app on my phone for setting things up with it, works well

**Comment by TBSniller** [comment]
Added spatial navigation in latest version (0.4.1)
