### ISSUE TITLE
Autostart PicCap

### ISSUE THREAD

**Issue by Laudings** [TBSniller/piccap#33]
Hey, i have the problem that Piccap doesn't start automaticly anymore by switching on the tv.
I have to start the PicCap App by hand, then it turns on. 
Quick Start+ is allready disabled.
I checked root, but everthing seems ok so far.
Maybe someone has an idea what could be the reason?

TV: OLED55BX9LB
Piccap: v2.3
Setting: libtvcapture + libhalgl / video capture on / grphic capture on 

Thank you vor your help!

**Comment by tuxuser** [comment]
Tracked in #25
