### ISSUE TITLE
Is PicCap only for native TV content, or also HDMI inputs?

### ISSUE THREAD

**Issue by andmib** [TBSniller/piccap#34]
This is going to be an extraordinarily basic question, so appologies. My presumption is that PicCap only works with native TV applications (i.e. Netflix on WebOS) but not any input devices, such as Apple TV. Is this correct?

**Comment by EyalRotem** [comment]
Read here-
https://hyperion-project.org/forum/index.php?thread/12347-piccap-hyperion-sender-app-ambilight-for-lg-webos-tvs/

Depending on your TV and webos version- DRM content might not work with PicCap.
HDMI inputs should work, though mine stopped, haven’t checked out why. 
read the wiki for more info, no need to open and close issues to get answers.
