### ISSUE TITLE
PICCAP not automatically recapturing when going from Non DRM Content to DRM content back to NON DRM

### ISSUE THREAD

**Issue by jr2fly** [TBSniller/piccap#35]
I been testing my setup and it works until I change apps. I can go from YouTube(led work) to Netflix (led off) to YouTube(led off) and the leds just stay off until I stop/start capture on piccap app.I know it’s not supposed to work with drm content but when I switch back to non drm content the leds stay off.  Is there  a way to make piccap restart capturing automaticly?

**Comment by tuxuser** [comment]
Should be addressed in https://github.com/webosbrew/hyperion-webos
