### ISSUE TITLE
Capturing stopped when goes back from screen saving

### ISSUE THREAD

**Issue by Thom-x** [TBSniller/piccap#39]
Hi,

First, thank you for your amazing work.

I'm having trouble with the screen saver.
When the screen saver starts, it closes both Hyperion and PicCap, that's OK.
But when it goes back to the screen:
-  Hyperion restart well
- PicCap doesn't send data any more

I have to stop/start the service to make it send data again.
BTW: When Hyperion restarts, I can see the light effect pattern, so it is connected to lights.

---
```
    "board_type": "M16P_DVB",
    "hardware_id": "HE_DTV_W18H_AFADABAA",
    "product_id": "OLED55B8PLA",
    "core_os_release": "4.4.0-12",
    "webos_manufacturing_version": "05.40.26",
```

**Comment by drbeat** [comment]
This is actually fixed by piccap 0.3.0 but that version is not available yet through homebrew shop.
You can install it manually

**Comment by EyalRotem** [comment]
> This is actually fixed by piccap 0.3.0 but that version is not available yet through homebrew shop.
> You can install it manually

Can you tell a noob how to install that version? I can’t figure out the whole webos rooting easily.
I did get a connection to the tv using ssh- what’s next?

**Comment by drbeat** [comment]
download this zip and extract the ipk
https://github.com/TBSniller/piccap/suites/6885815632/artifacts/266702117

upload it to the /tmp folder of your tv via scp

run this command
`luna-send -i -f luna://com.webos.appInstallService/dev/install '{"id":"org.webosbrew.piccap","ipkUrl":"/tmp/org.webosbrew.piccap_0.3.0_all.ipk","subscribe":true}'`

open the app on the tv and see if you get root/can change the settings
if you dont get the root status you need to elevate the process via this command

/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service/elevate-service org.webosbrew.piccap.service

**Comment by Thom-x** [comment]
Thank you, if it is only a matter of installing it manually, no big deal. 👌👍

**Comment by Thom-x** [comment]
I installed it, but it's not working at all.
I cannot even save the IP address. After a reboot, everything is reset.
I Let all options by default. :/

**Comment by drbeat** [comment]
As I said you need to elevate the process.

MAUGIN Thomas ***@***.***> schrieb am So., 3. Juli 2022,
21:37:

**Comment by Thom-x** [comment]
After some test I can see that the capturing has much more delay, like half a second. Is there any option to enable to fix that ? 

I tried lowering the resolution and changing FPS/VSync, but no effect.

**Comment by SkalkaA** [comment]
Hi, I've the same issue, long delay in 0.3.0, and capture running under 10fps. Is there any fix? Thanks

**Comment by drbeat** [comment]
Lower the resolution, turn off vsync and turn on no freeze fix from quick
fixes.

SkalkaA ***@***.***> schrieb am Do., 11. Aug. 2022, 22:07:

**Comment by TBSniller** [comment]
As mentioned by @drbeat this should be fixed in latest version. It's now also available in Homebrew Channel.
