### ISSUE TITLE
Piccap says its capturing "true" and Hyperion is receiving a connection to flatbuffers but nothing.

### ISSUE THREAD

**Issue by raujaku** [TBSniller/piccap#4]
Model: LGCX77PUA
Firmware: 03.21.18
WebOS: 5.21-290906

root@LGwebOSTV:~# /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos_libvt -a "hyp-ip"
[EGL] Display, major = 1, minor = 4
[EGL] Surface size: 192x108
[EGL] init complete
[VT] VT_CreateVideoWindow
[VT] window_id=0
[VT] VT_AcquireVideoWindowResource
[VT] resource_id=-4011
[VT] VT_CreateContext
[VT] VT_CreateContext Failed

root@LGwebOSTV:/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service# ./hyperion-webos_libvtcapture
./hyperion-webos_libvtcapture: error while loading shared libraries: libhalgal.so.1: cannot open shared object file: No such file or directory

root@LGwebOSTV:/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service# whereis libhalgal.so.1
libhalgal.so: /usr/lib/libhalgal.so /usr/lib/libhalgal.so.0 /usr/lib/libhalgal.so.2

**Comment by TBSniller** [comment]
Could you please try to update to PicCap v0.1.0? I removed the versionsinfo for this lib while compiling. It now also runs on a TV of another one in the OpenLG Discord. 
Please let me know if its fixed now

**Comment by raujaku** [comment]
That seemed to fix the issue. Working perfectly now. Thank you!
