### ISSUE TITLE
Webos 3.4 M16_DVB piccap 0.2.3 and 0.3.0 (Build#55) not running

### ISSUE THREAD

**Issue by szbbalint** [TBSniller/piccap#40]
Hey, i have installed piccam like a year ago on a different TV, it work like a charm, but can't make work this one.
"board_type": "M16_DVB",
    "hardware_id": "HE_DTV_W16M_AFADABAA",
    "product_id": "55UH950V-ZA",
    "core_os_release": "3.4.0-6107",
i have tried it with the version from homebrew chanel (0.2.3) but it gives me the following:

luna-send -n 1 -f luna://org.webosbrew.piccap.service/isRunning '{}'
{
    "returnValue": true,
    "isRunning": true
}

with the latest 0.3.0 build#55 get the following:

luna-send -n 1 -f luna://org.webosbrew.piccap.service/isRoot '{}'
{
    "errorCode": -1,
    "returnValue": false,
    "errorText": "Unknown method \"isRoot\" for category \"/\""
}

What else should i try? Thank You :)

**Comment by TBSniller** [comment]
Please check out latest version (currently 0.4.1) this is tested working on webOS 3.4.
