### ISSUE TITLE
No loading status y dosn't start

### ISSUE THREAD

**Issue by emiguerol** [TBSniller/piccap#44]
Hi

Version software: 05.60.30
Tv: 55UH770V
Version WebOs: 3.4.0-5710

In homebrew channel (0.5.1) appears "Root status OK"

1º I install piccap, select autostart and restart tv. 
2º Install HyperHDR, select autostar and restart tv
3º Install Backends, select all steps with "success" result 
4º Launch Piccap

When launch piccap I see that de status is constantly appears "loading". I push to start and appears the message:

Failed: 
{"returnValue":false,"errorCode":-1,"errorText":"Denied method call \"start\" for category \"/\""}

It also happens that when I push the save button, it stays status "saving" all time

Thanks

**Comment by TBSniller** [comment]
Hey, 
at current release version we don't have support for WebOS 3.4.0.
We provide support in our development builds. Latest non testing version can be found here: https://github.com/TBSniller/piccap/actions/runs/2704563747

**Comment by emiguerol** [comment]
I have already installed version 3.0 of piccap and updated the files in the /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service with https://github.com/TBSniller/piccap/suites/7439267853/artifacts/304144090 but it still doesn't work. Any idea?

**Comment by TBSniller** [comment]
Please checkout latest version in Homebrew Channel. It was tested successfully on webOS 3.4 TVs. If you still have problems try to fully uninstall PicCap before an installation.
