### ISSUE TITLE
Add setting for local unix socket

### ISSUE THREAD

**Issue by TBSniller** [TBSniller/piccap#46]
In https://github.com/webosbrew/hyperion-webos/pull/86 we have a new setting available. Thanks to @sundermann!

We have to add this to settings page in PicCap. 
Idea: Checkbox below IP address field -> If ticked, disable IP/Port inputs

**Comment by tuxuser** [comment]
Correction, only disable the port input field. The address field is still needed to take the target Unix socket path.

Maybe rename the field in UI dynamically, depending on unix-socket setting.

**Comment by alucryd** [comment]
@TBSniller The PR works fine here, nice job :)

**Comment by TBSniller** [comment]
Fixed in #55
