### ISSUE TITLE
What do you think regarding use of PicCap on long run?

### ISSUE THREAD

**Issue by stiw47** [TBSniller/piccap#50]
Actually, this is not an issue, but I don't know where else would ask. My apologize if this is not proper place, and please be free to close it immediately.

Model: LG OLED55C11LB
WebOS version: 6.2.0-35 (kisscurl-kavir)
System version: 3.21.20

Rooted with https://rootmy.tv/ and installed PicCap app from Homebrew Channel. Current version of PicCap on my TV is v0.4.1

App is very good, everything is working like a charm and I am very happy that I have single "capture device" for all apps, HDMI inputs, etc. BIG THANKS for that!

However, when I login to TV via SSH and look to processes via `top` command, I can see that `hyperion-webos` process is using ~115% of CPU most of the time. Of course, top is showing more than 100% because of multi core processor I think, but global remote monitoring of MobaXterm is also showing noticeable higher usage than usual, ~40% for whole CPU with all their cores.

![image](https://user-images.githubusercontent.com/3337416/192965859-60b314a2-883b-47fe-a45c-d4c4bfda424b.png)

On the other hand, if I turn off PicCap service, `hyperion-webos` process is normally not listed in `top` any more, and global CPU usage is about 5-9%, with certain short spikes up to 35-40%. Please note, for both cases, I'm talking about TV "IDLE" state, i.e. when TV is on home launcher, not playing any video stream, etc.

I suppose this maybe could be tweaked little bit and we could got less CPU usage, but I also know that this cannot be too much and that such a type of service must use more CPU resources than other services. My question is actually for community: What do you think, is it risky to use this on long run? I mean, I'm using this combo as daily driver since April this year: Hyperion on the other PC (home server) + PicCap on TV. Every time when I turn on TV, PicCap is auto started, I have ambilight and I'm happy 😁. But on the other hand, my TV CPU is working on 40-50% all the time. Could this shorten it's life?

Thanks.

**Comment by TBSniller** [comment]
Hey there,
please take a look at latest release (0.4.2). We actually used a toolchain, which caused high CPU usage, because of missing runtime optimizations. You can also take a look at this ticket, where it is discussed further and also post your insights, if they are still applying: https://github.com/webosbrew/hyperion-webos/issues/94
Furthermore this issue is related to `hyperion-webos`, which is the background service. This project is for `PicCap`, the frontend which manages `hyperion-webos` in a user friendly way.
