### ISSUE TITLE
Link to DIY_Ambilight.md missing

### ISSUE THREAD

**Issue by josbmw** [TBSniller/piccap#60]
Hi,

This link [DIY_Ambilight.md d](https://github.com/TBSniller/piccap/blob/main/DIY_Ambilight.md) does not seem to work anymore...
I have all the software installed on my LG, but how do I connect the hardware?

Thnx,

Jos

**Comment by mksy** [comment]
https://github.com/TBSniller/piccap/blob/release/DIY_Ambilight.md

**Comment by TBSniller** [comment]
You're right. Have fixed it thanks!
