### ISSUE TITLE
[QUESTION] Expected lag/delay?

### ISSUE THREAD

**Issue by psychowood** [TBSniller/piccap#62]
Hi,
can you share the lag you experience (f any) with piccap in your configuration?

I'm currently on wifi-connected wled and I tried both hyperion and hyperhdr, either local on my TV (LG C9) and on a lan server, and I see about 0.5s, which looks like is higher than online user videos.

Attached is a sample video using the embeded youtube webos app, the delay is more or less the same regardless of the source (either internal apps or external hdmi sources in game mode).

Thanks in advance.

https://user-images.githubusercontent.com/115389/205592494-acce57f8-d6b1-4ab4-87be-c1fe79d56bc9.mp4

**Comment by TBSniller** [comment]
Hey @psychowood, 
can you please show a video how it looks like in hyperion video preview? 
And which resolution have you set up in PicCap?

**Comment by Dammouz** [comment]
Hello,

I also have a LG C9. I have no lag for the moment. I have not yet finished to build the final frame for the leds (still a proto with bamboo), but all the software part is done.
If it could help, here are my settings :

 - LG TV
   Model: LG 55C9
   Software: 05.20.07
   Netword: ethernet

 - Homebrew
   WebOSBrew version: 0.5.1

 - PicCap
   PicCap version: 0.4.2
   Resolution: 320x180
   Max FPS: 25 (I force it to 25 when I increased the resolution)

 - hyperion.ng
   Hyperion.Ng (TV app) version: 0.1.8
   Hyperion (web interface) version: 2.0.14

 - Leds
   LED type: APA102
   Number: 158
   Managed by: ESP32
   Network: Wi-Fi (2.4 GHz)

All other settings are the one by default on the several apps.

I take this opportunity to thanks everyone working on this amazing project !

**Comment by psychowood** [comment]
@Dammouz Thanks, I'll check my settings. Any filter applied on Hyperion.NG (I'm currently using HyperHDR that should be even faster)?

@TBSniller Sorry for the delay, I'll provide asap the video. Anything specific to look out for? If it is a network delay I expect to see the Hyperion leds to be in sync with the preview...

**Comment by broekhuisg** [comment]
Hi. I have the same problem as you. The preview is stuttering, so it has to be piccap that doesn't send the video to hyperion. 
Did a few tests with changing the resolution, but that didnt help...

**Comment by TBSniller** [comment]
Hey there, 
is it possible that you guys are using 5Ghz Wifi?
You can follow this Discord thread to get to know why I'm asking: https://discord.com/channels/407937994037919756/939893245767454740

**Comment by psychowood** [comment]
@TBSniller I can't open the link, not sure why...

<img width="528" alt="image" src="https://github.com/TBSniller/piccap/assets/115389/68cd1172-cc3b-4ff7-96bc-c890ecd4433b">

Anyways, if I remember correctly my TV is connected over 5Ghz, thanks for the hint. I'll try it in a few weeks to change it to 2.4GHz when I get home.

**Comment by TBSniller** [comment]
@psychowood Oh funny
Here you go: 
![image](https://github.com/TBSniller/piccap/assets/51515147/16ab153e-b162-4ae2-9c8a-c06fe27e48c1)
![image](https://github.com/TBSniller/piccap/assets/51515147/a5a2e776-49e4-4e04-aa0f-eb45c25249ac)
![image](https://github.com/TBSniller/piccap/assets/51515147/d3253bc8-3230-44d8-a616-fc4792a455cc)

More or less an issue at LG
