### ISSUE TITLE
Broken picture

### ISSUE THREAD

**Issue by marvandorth** [TBSniller/piccap#65]
Hello,

I've seen the other issues closed, but i do have weird distorted picture in HyperHDR when videoplayback is coming from an hdmi input.
Youtube and Netflix etc. working fine. It's the same issue as #26 or #63

**Comment by TBSniller** [comment]
Hey, 
have you already tried to change the resolution as adviced in comments? 
If so, which ones did you tried?

**Comment by marvandorth** [comment]
Hi,
I've tried a lot but it was, in the end, a faulty LUT installation.
Thanks anyways!
