### ISSUE TITLE
Receiver: Disconnected

### ISSUE THREAD

**Issue by bkbartk** [TBSniller/piccap#76]
Probably it's me but  I can't get it to work
I tried installing either Hyperion or HyperHDR(not on the same time) on my WebOS tv.
Then configure piccap to 127.0.0.1 port 19400
but it keeps saying receiver:disconnected.

In the webinterface op hyperrion or HyperHDR no screencaptures are showing up.

The goal is the grep the RGB value in homeassistant so I can sync other devices with it. but probably I'm missing some crucial point here.

Also, but this is another thing, I don't own a magic remote, and using the other remote it's inpossible the leave the checkbox fields under settings, therefore you cannot change the checkboxed because you won't be able to navigate to save.

**Comment by TBSniller** [comment]
Hey there, 
can you confirm you can reach Hyperion/HyperHDR configuration page? 
Can you please also provide some more information regarding your TV? 
`grep -h -E '"(hardware_id|core_os_release|product_id|webos_manufacturing_version|board_type)"' /var/run/nyx/*`
Please also tell us which capture backend is used. You can get this Info from bottom left corner. 

Normal remote navigation should work in latest PicCap releases.

**Comment by bkbartk** [comment]
can you confirm you can reach Hyperion/HyperHDR configuration page?
![image](https://github.com/TBSniller/piccap/assets/17070805/2741f16c-3f6e-4e73-b2e4-e0600f3c4d4a)
`yes I can on port 8090
Can you please also provide some more information regarding your TV?
grep -h -E '"(hardware_id|core_os_release|product_id|webos_manufacturing_version|board_type)"' /var/run/nyx/*
```
webOS TV 4.9.7 LGwebOSTV

~ # grep -h -E '"(hardware_id|core_os_release|product_id|webos_manufacturing_ver
sion|board_type)"' /var/run/nyx/*
    "board_type": "K5LP_DVB",
    "hardware_id": "HE_DTV_W19P_AFADABAA",
    "product_id": "49UM7050PLF",
    "core_os_release": "4.9.7-17",
    "webos_manufacturing_version": "05.30.40",
~ #

```
Please also tell us which capture backend is used. You can get this Info from bottom right corner.
the full text says:
`State: Status info refreshed | Receiver: Disconnected | UI: Capturing with libgm_backend.so | Video: Capturing with libdile_vt_backend.so | FPS 30.10`

Normal remote navigation should work in latest PicCap releases.
-according to homebrew I have version 0.4.3 installed
I can change all I need, but not the checkboxes "Local socket", "Autostart", "VSync" because as soon as I chane it the focus is lockec and I can't move away using the arrows.

**Comment by bkbartk** [comment]
I typed the IP again, and now Receiver says "connected"
So I guess a leading or trailing space,
sorry to bother you with this.

for the checkbox unfortunately, I can't get "autostart" to be enabled,

**Comment by bkbartk** [comment]
I downloaded an app on my phone which can handle the magic pointer, so all setting I can use now.
