### ISSUE TITLE
LG Live Preview Lag

### ISSUE THREAD

**Issue by JoelBrenstrum** [TBSniller/piccap#80]
Every few seconds my live preview experiences a lag spike
https://github.com/TBSniller/piccap/assets/4349208/fbaea980-70d5-4a91-b4bb-77e6ffb4044e

This affects the LEDS as well.

I have tried running HyperHDR and Hyperion on a separate server and on the TV directly. Both still have the lag. Which leads me to think it is piccap.

I have tried lowering the fps to 15, with no effect and lowering the resolution, with no effect.

Do you have any ideas for me?

**Comment by JoelBrenstrum** [comment]
#62 Turns out it was the 5g wifi. Initially i wrote this off as the server was hosted on the TV but the communication to the my laptop and WLED is not. 

Now it is working perfectly!

**Comment by TBSniller** [comment]
@JoelBrenstrum I would suggest you to move away from wifi and use an ethernet cable 

If you cannot, it could be a try to check your routers used wifi channels and switch to a non frequently used on or even set a static one to avoid automatic channel switches. 

Another idea is to use Hyperion/HyperHDR server again directly on the TV. With HyperHDR you have the ability to use a local socket which will also give you less latency
