### ISSUE TITLE
Piccap not staying connected to pi 3b

### ISSUE THREAD

**Issue by FTBSchnitzel** [TBSniller/piccap#85]
Device - 65UM7050PLA
webOS 4.10.0
OTA ID HE_DTV_W19P_AFADABAA
SoC k5lp

Config
{"priority":150,"nohdr":false,"nopowerstate":false,"backend":"auto","unix-socket":false,"address":"192.168.178.28","port":19400,"width":320,"height":180,"quirks":0,"fps":30,"vsync":true,"autostart":false,"nogui":false,"novideo":false,"uibackend":"auto"}

Pi 3b non plus version
Hyperhdr 20.0.0.0
both are on 2.4ghz 

It is connected for about 2-7s and then disconected 2-7s which makes the led just turn of and on. Also the preview is pretty laggy

**Comment by TBSniller** [comment]
This sounds like a common wifi issue.
Can you please try to use Hyperion/HyperHDR as a first attempt directly on the TV? If the preview is working fine here, it might be related to your local network. In this case you can also try to use an ethernat cable
