### ISSUE TITLE
PicCap Autostart not working

### ISSUE THREAD

**Issue by irqnet** [TBSniller/piccap#86]
I've just rooted my 86UM7600PLB running WebOS 05.40.45

In general PicCap is working with a HyperionHDR instance hosted on Proxmox flawlessly.

Just the autostart of PicCap seems not to work, so calling the app manually is mandatory on every start of the TV. It' just opening the app and the service is starting immediately without any button press needed.

![shot121640](https://github.com/user-attachments/assets/db56470f-ae6a-4210-89bb-5a5464ae661c)

Checking via telnet if the script probably don't have sufficient rights, pushed me into the direction if the autostart script may fail on TV startup.

`/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service # ./piccapautostart
/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service # {
    "errorCode": -1,
    "returnValue": false,
    "errorText": "Unknown method \"isRunning\" for category \"/\""
}
`

Starting the binary manually is throwing some errors, but ambilight is working as expected:

![image](https://github.com/user-attachments/assets/2d110e6c-0e49-4f3f-b602-d0aab2f519c4)

**Comment by TBSniller** [comment]
Can you please check if you have a file at `/var/lib/webosbrew/init.d/piccapautostart`? This file is needed and executed on startup by homebrew channel.
You can also run `luna-send -n 1 -f luna://org.webosbrew.piccap.service/isRunning '{}'` without opening the app, which then should start the capture. If this works, there will be a problem with the autostart behaviour. You could here try to disable Quick Start+. 

```
/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service # { "errorCode": -1, "returnValue": false, "errorText": "Unknown method \"isRunning\" for category \"/\"" } 
```
Your output is kind of expected as we only need to trigger the exposed luna service, which automatically will run then the binary if its not running at all.
