### ISSUE TITLE
Video grabber flickers with artefacts

### ISSUE THREAD

**Issue by Jejebond** [TBSniller/piccap#87]
Hi,

I have a strange issue since i try to go 4k 120hz HDR with a new optical HDMI cable (RUIPRO, 20 meters cable) between my LG C9 and my PC.

https://github.com/user-attachments/assets/315267af-a32d-430e-921b-20150ec40079

Here is what the grabber shows :

![Capture d'écran 2024-10-20 091149](https://github.com/user-attachments/assets/849a840b-188f-4522-b1c9-9413693a79ab)

But the TV is showing clear image, 4k 120hz HDR without issue.

I've tried Vsync, lowering resolution, lowering FPS in Picap, same results.
If i try to set my PC back to 1080p 120hz, it won't work every time. Could it be VRR then ? some other tech interfering ? A setting on my LG C9 ?

I suspect going 120hz gives me this issue every time, even in 1080P.

Is this a know issue ? Any ideas ?

Thanks a lot

**Comment by TBSniller** [comment]
@Jejebond Do I understand it correctly, that you do not have these problems with a normal HDMI cable?

**Comment by Jejebond** [comment]
> @Jejebond Do I understand it correctly, that you do not have these problems with a normal HDMI cable?

Haven't tried but i'm using HyperHDR beta now and issue is gone.

**Comment by TBSniller** [comment]
Nice, thanks for info!
